### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by Littleiii** [hss01248/PhotoOut#8]
选择照片的时候,点击所有照片,会出现空指针,  异常信息:     java.lang.NullPointerException
                                                                        at me.iwf.photopicker.adapter.PopupDirectoryListAdapter.getView(PopupDirectoryListAdapter.java:55)
                                                                        at android.support.v7.widget.ListViewCompat.measureHeightOfChildrenCompat(ListViewCompat.java:307)
                                                                        at android.support.v7.widget.ListPopupWindow.buildDropDown(ListPopupWindow.java:1288)

**Comment by yc654084303** [comment]
同样问题，你是怎么解决的

**Comment by yc654084303** [comment]
Process: com.hnscinfo.xfb, PID: 13686
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.squareup.picasso.RequestCreator com.squareup.picasso.RequestCreator.tag(java.lang.Object)' on a null object reference
        at com.hss01248.picasso.PicassoLoader.request(PicassoLoader.java:97)
        at com.hss01248.image.config.SingleConfig.show(SingleConfig.java:191)
        at com.hss01248.image.config.SingleConfig.access$2500(SingleConfig.java:16)
        at com.hss01248.image.config.SingleConfig$ConfigBuilder.into(SingleConfig.java:395)
        at me.iwf.photopicker.adapter.PhotoGridAdapter.onBindViewHolder(PhotoGridAdapter.java:119)
        at me.iwf.photopicker.adapter.PhotoGridAdapter.onBindViewHolder(PhotoGridAdapter.java:28)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6781)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.try
